blank_issues_enabled: false
contact_links:
  -
    name: "Funding Open Source Software 路 Flourd"
    url: https://funding.flourd.com
    about: "Information regarding Open Source Software and its funding."
  -
    name: "Code of Conduct 路 Flourd"
    url: https://conduct.flourd.com
    about: "Community Code of Conduct information."
  - 
    name: "Community Support 路 Flourd"
    url: https://community.flourd.com
    about: "Please ask and answer questions here."
  - 
    name: "Security Bug Bounty 路 Flourd"
    url: https://bugs.flourd.com
    about: "Please report security vulnerabilities here."
