name: Snek
env:
  ASSETS: "./.github/assets"
  REPOSITORY: ${{github.repository}}
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
on:
  workflow_dispatch:
  # schedule:
    # - cron: "20 4 * * *" 
  # push:
    # branches
      # - main
jobs:
  build:
    name: "Create contribution sneks"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - 
        name: "Create assets directory"
        run: |
          [ ! -d $ASSETS ] && 
            mkdir -p -v $ASSETS && 
              printf "\n\e[1;32m✅️  Successfully created %s\e[0m\n\n" $ASSETS
      - 
        name: "Generate Assets"
        uses: Platane/snk@master
        with:
          github_user_name: ${{github.repository_owner}}
          svg_out_path: assets/snek.svg
          gif_out_path: assets/snek.gif
      - 
        name: "Upload Artifacts"
        uses: actions/upload-artifact@v2.3.1
        with:
          name: assets
          path: .github/assets/snek.*
          if-no-files-found: warn
          retention-days: 14
          
  update:
    name: "Push updated sneks to main"
    runs-on: ubuntu-latest
    needs: [build]
    env:
      BRANCH: main
      DRY_RUN: true
      JEKYLL: false
      VERBOSE: true
      COMMIT_MSG: "[chore] update contribution sneks"
      COMMITTER: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
      AUTHOR: "Nicholas Berlette <nick@berlette.com>"
    steps:
      - 
        name: "Checkout Repository"
        uses: actions/checkout@v2
      -
        name: "Download Artifacts"
        uses: actions/download-artifact@v2.1.0
        with:
          name: assets
          path: .github/assets
      - 
        name: "Ensure .github/assets Exists"
        run: |
          [ ! -d .github/assets ] && 
            mkdir -p -v .github/assets && 
              printf "\n\e[1;32m✅️  Successfully created %s\e[0m\n\n" "./github/assets"
      -
        name: "Delete previous versions"
        run: |
          rm -rf .github/assets/snek.* &&
            printf "\n\e[1;32m✅️  Old files removed from %s\e[0m\n\n" ".github/assets"
      - 
        name: "Commit + Push Updates"
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          # domain: github.com
          repo: $REPOSITORY
          target_branch: $BRANCH
          build_dir: .
          keep_history: true
          author: $AUTHOR
          committer: $COMMITTER
          commit_message: $COMMIT_MSG
          jekyll: $JEKYLL
          dry_run: $DRY_RUN
          verbose: $VERBOSE
          
