name: Snek
on:
  workflow_dispatch:
  schedule:
    - cron: "20 4 * * *" 
  push:
    branches:
      - main
jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          path: ./
      - name: Ensure assets dir
        run: mkdir -p -v ./.github/assets
      - name: Make Snek
        uses: Platane/snk@master
        with:
          github_user_name: ${{github.repository_owner}}
          svg_out_path: ./.github/assets/snek.svg
          gif_out_path: ./.github/assets/snek.gif
      - name: Verified commit
        uses: swinton/commit@v2.0.0
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          files: |
            ./.github/assets/snek.svg
            ./.github/assets/snek.gif
          commit-message: "[action] update: .github/assets/snek.{gif,svg}"
